#!/bin/sh
#
# vyatta-cjdns - A cjdns package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2015 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ `lsb_release -c | grep "jessie" | wc -l` -ne 1 ];
then
    echo "This script is supported on jessie only"
    exit -1
fi

echo "Checking if emdebian repository is a configured apt source..."
if [ `cat /etc/apt/sources.list | grep "http://emdebian.org/tools/debian/ jessie" | wc -l` -lt 1 ];
then
    echo "Adding emdebian.org repository to apt sources"
    sudo echo "deb http://emdebian.org/tools/debian/ jessie main" >> /etc/apt/sources.list
fi

echo "Checking if Codescape GNU Tools Package for MIPS is in /opt..."
if [ ! -d "/opt/mips-mti-linux-gnu/2015.06-05/" ];
then
    echo "Downloading and unpacking Codescape GNU Tools Package for MIPS into /opt"
    wget -P /tmp http://codescape-mips-sdk.imgtec.com/components/toolchain/2015.06-05/Codescape.GNU.Tools.Package.2015.06-05.for.MIPS.MTI.Linux.CentOS-5.x86_64.tar.gz
    sudo tar -zxf /tmp/Codescape.GNU.Tools.Package.2015.06-05.for.MIPS.MTI.Linux.CentOS-5.x86_64.tar.gz -C /opt
fi

PATH=/opt/mips-mti-linux-gnu/2015.06-05/bin:$PATH

echo "Building vyatta-cjdns..."
cd vyatta-cjdns && \
    PREFIX='mips-mti-linux-gnu-' PKGARCH='mips' make cross -e && \
    cd ..
