#!/bin/sh

if [ `dpkg --status tzdata | grep Provides | cut -f 2 -d '-' | grep squeeze | wc -l` -ne 1 ];
then
    echo "This script is supported on squeeze only"
    exit -1
fi

echo "Checking if squeeze archive repository is a configured apt source..."
if [ `cat /etc/apt/sources.list | grep "http://archive.debian.org/debian/ squeeze" | wc -l` -ne 1 ];
then
    echo "Adding squeeze archive repository to apt sources"
    sudo echo "deb http://archive.debian.org/debian/ squeeze main non-free" >> /etc/apt/sources.list
fi

echo "Checking if python2.7 is installed..."
if [ `which -a python2.7 | wc -l` -lt 1 ];
then
    echo "Downloading and building python2.7"
    wget -P /tmp https://www.python.org/ftp/python/2.7/Python-2.7.tgz
    tar -zxf /tmp/Python-2.7.tgz -C /tmp
    PWD=$(shell pwd)
    cd /tmp/Python-2.7/
    ./configure
    make
    sudo make install
    cd $PWD
fi

echo "Checking if sudo is installed..."
dpkg -s sudo >/dev/null 2>1
if [ $? -eq 1 ];
then
    echo "Installing sudo"
    su -c "apt-get update; apt-get install -y sudo"
fi

echo "Checking if build-essential is installed..."
dpkg -s build-essential >/dev/null 2>1
if [ $? -eq 1 ];
then
    echo "Installing build-essential"
    sudo apt-get update
    sudo apt-get install -y build-essential
fi

echo "Building vyatta-cjdns..."
cd vyatta-cjdns && \
    make native && \
    cd ..
