#!/bin/sh
#
# vyatta-cjdns - A cjdns package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2015 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ `lsb_release -c | grep "jessie" | wc -l` -ne 1 ];
then
    echo "This script is supported on jessie only"
    exit -1
fi

echo "Checking if emdebian repository is a configured apt source..."
if [ `cat /etc/apt/sources.list | grep "http://emdebian.org/tools/debian/ jessie" | wc -l` -lt 1 ];
then
    echo "Adding emdebian.org repository to apt sources"
    sudo echo "deb http://emdebian.org/tools/debian/ jessie main" >> /etc/apt/sources.list
fi

echo "Checking if emdebian repository GPG key is trusted..."
if [ `apt-key list | grep Emdebian | wc -l` -lt 1 ];
then
    echo "Key not trusted, installing"
    wget -qO - http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
fi

echo "Checking if 'mipsel' is configured dpkg foreign architecture...."
if [ `dpkg --print-foreign-architectures | grep "mipsel" | wc -l` -lt 1 ];
then
    echo "Adding mipsel to dpkg architectures"
    sudo dpkg --add-architecture mipsel
fi

echo "Checking if crossbuild-essential-mipsel is installed..."
dpkg -s crossbuild-essential-mipsel >/dev/null
if [ $? -eq 1 ];
then
    echo "Installing crossbuild-essential-mipsel"
    sudo apt-get update
    sudo apt-get install -y crossbuild-essential-mipsel
fi

echo "Building vyatta-cjdns..."
cd vyatta-cjdns && \
    PREFIX='mipsel-linux-gnu-' PKGARCH='mipsel' make cross -e && \
    cd ..
