#!/bin/sh
#
# vyatta-cjdns - A cjdns package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2015 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -f /config/cjdroute.$1.conf ]; then
	echo "cjdns generate conf: /config/cjdroute.$1.conf already exists, leaving alone"
else
	echo "cjdns generate conf: $1"

	/opt/vyatta/sbin/cjdroute --genconf | /opt/vyatta/sbin/cjdroute --cleanconf > /config/cjdroute.$1.conf
	/opt/vyatta/sbin/vyatta-cjdns-updateconf $1 setStandardConfiguration

	cli-shell-api inSession
	if [ $? -ne 0 ]; then
		echo "Unable to set up API session to read back config"
	else
		${vyatta_sbindir}/my_set interfaces cjdns $1 publickey `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getPublicKey`
		${vyatta_sbindir}/my_set interfaces cjdns $1 privatekey `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getPrivateKey`
		${vyatta_sbindir}/my_set interfaces cjdns $1 ipv6 `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getIPv6Address`
		${vyatta_sbindir}/my_set interfaces cjdns $1 admin-bind-address `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getAdminAddress`
		${vyatta_sbindir}/my_set interfaces cjdns $1 admin-password `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getAdminPassword`
	fi
fi
