#!/bin/sh

if [ `ls /config/cjdroute.*.conf 2>/dev/null | wc -l` -gt 0 ];
then
    ls /config/cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $3}' | while read file;
    do
        if [ `cat /var/run/cjdroute.$file.pid | xargs pgrep -P 2>/dev/null | wc -l` -eq 0 ];
        then
            echo "The cjdroute daemon for $file was not running, restarting..."
            nohup nice -5 /opt/vyatta/sbin/cjdroute --nobg &>/tmp/cjdroute.$file.log < /config/cjdroute.$file.conf &
            echo $! > /var/run/cjdroute.$file.pid
        fi
    done
fi
