#!/usr/bin/python

import json
import sys

data = {}

with open('/config/cjdroute.' + sys.argv[1] + '.conf') as data_file:
    data = json.load(data_file)

def getAdminAddress():
    print data['admin']['bind']

def getAdminPassword():
    print data['admin']['password']

def getPublicKey():
    print data['publicKey']

def getPrivateKey():
    print data['privateKey']

def getIPv6Address():
    print data['ipv6']

def showIdentity():
    print "IPv6 address: " + data['ipv6']
    print "Public key: " + data['publicKey']
    print "Private key: " + data['privateKey']

try:
    if sys.argv[2] == "getAdminAddress": getAdminAddress()
    if sys.argv[2] == "getAdminPassword": getAdminPassword()
    if sys.argv[2] == "getPublicKey": getPublicKey()
    if sys.argv[2] == "getPrivateKey": getPrivateKey()
    if sys.argv[2] == "getIPv6Address": getIPv6Address()
    if sys.argv[2] == "showIdentity": showIdentity()
except IndexError:
    print "Incorrect number of parameters supplied"
