#!/usr/bin/python

import json
import sys
import os

configfile = '/config/cjdroute.' + sys.argv[1] + '.conf'
data = {}

try:
    with open(configfile) as data_file:
        data = json.load(data_file)
except:
    os.system('/opt/vyatta/sbin/cjdroute --cleanconf < ' + configfile + ' > ' + configfile + ".tmp")

    try:
        with open(configfile + ".tmp") as data_file:
            data = json.load(data_file)
    except:
        print "Unable to parse " + configfile + " - file malformed?"
        exit -1
    else:
        os.system("mv " + configfile + ".tmp " + configfile)

def getAdminAddress():
    print data['admin']['bind']

def getAdminPassword():
    print data['admin']['password']

def getPublicKey():
    print data['publicKey']

def getPrivateKey():
    print data['privateKey']

def getIPv6Address():
    print data['ipv6']

def showIdentity():
    print "IPv6 address: " + data['ipv6']
    print "Public key: " + data['publicKey']
    print "Private key: " + data['privateKey']

try:
    if sys.argv[2] == "getAdminAddress": getAdminAddress()
    if sys.argv[2] == "getAdminPassword": getAdminPassword()
    if sys.argv[2] == "getPublicKey": getPublicKey()
    if sys.argv[2] == "getPrivateKey": getPrivateKey()
    if sys.argv[2] == "getIPv6Address": getIPv6Address()
    if sys.argv[2] == "showIdentity": showIdentity()
except IndexError:
    print "Incorrect number of parameters supplied"
