#!/bin/sh

echo "cjdns generate conf: $1"

/opt/vyatta/sbin/cjdroute --genconf | /opt/vyatta/sbin/cjdroute --cleanconf > /config/cjdroute.$1.conf
/opt/vyatta/sbin/vyatta-cjdns-updateconf $1 setStandardConfiguration


cli-shell-api inSession
if [ $? -ne 0 ]; then
	echo "Unable to set up API session to read back config"
else
	${vyatta_sbindir}/my_set interfaces cjdns $1 publickey `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getPublicKey`
	${vyatta_sbindir}/my_set interfaces cjdns $1 privatekey `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getPrivateKey`
	${vyatta_sbindir}/my_set interfaces cjdns $1 ipv6 `/opt/vyatta/sbin/vyatta-cjdns-readconf $1 getIPv6Address`
fi
