#!/bin/sh
#
# vyatta-cjdns - A cjdns package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2015 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ ! -z $1 ];
then
    if [ `cat /var/run/cjdroute.$1.pid 2>/dev/null | wc -l` -gt 0 ];
    then
        echo -n "Stopping cjdns interface $1... "
        pkill -P `cat /var/run/cjdroute.$1.pid 2>/dev/null`
        if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK.";
        else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
    fi

    if [ `ls /config/cjdroute.*.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        echo -n "Starting cjdns interface $1... "
        nohup nice -5 /opt/vyatta/sbin/cjdroute --nobg &>/tmp/cjdroute.$1.log < /config/cjdroute.$1.conf &
        if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$1.pid; echo "OK.";
        else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
    fi
else
    if [ `pgrep cjdroute 2>/dev/null | wc -l` -gt 0 ];
    then
        ls /var/run/cjdroute.*.pid | awk -v FS="(cjdroute.|.pid)" '{print $2}' | while read pid;
        do
            echo -n "Stopping running cjdns interface $pid... "
            pkill -P `cat /var/run/cjdroute.$pid.pid`
	    if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.*.pid &>/dev/null; echo "OK.";
	    else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
        done
    fi

    if [ `ls /config/cjdroute.*.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        ls /config/cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $3}' | while read file;
        do
            echo -n "Starting cjdns interface $file... "
            nohup nice -5 /opt/vyatta/sbin/cjdroute --nobg &>/tmp/cjdroute.$1.log < /config/cjdroute.$file.conf &
            if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$file.pid; echo "OK.";
            else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
        done
    fi
fi
